const types = {
  GET_LINKS: 'GET_LINKS',
  GET_LINKS_SUCCESS: 'GET_LINKS_SUCCESS',
  ADD_LINK: 'ADD_LINK',
  ADD_LINK_SUCCESS: 'ADD_LINK_SUCCESS',
  DELETE_LINK: 'DELETE_LINK',
  DELETE_LINK_SUCCESS: 'DELETE_LINK_SUCCESS',
  UP_VOTE_LINK: 'UP_VOTE_LINK',
  UP_VOTE_LINK_SUCCESS: 'UP_VOTE_LINK_SUCCESS',
  DOWN_VOTE_LINK: 'DOWN_VOTE_LINK',
  DOWN_VOTE_LINK_SUCCESS: 'DOWN_VOTE_LINK_SUCCESS',
  SET_SELECTED_FILTER: 'SET_SELECTED_FILTER'
}

export default types
